name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: testing
        run: |
          python -m venv venv
          . ./venv/bin/activate
          pip install -r requirement.txt
          pytest
